import Head from "next/head";
import About from "../components/About";
import Client from "../components/Client";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Products from "../components/Product";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CV. Rizky Fitri Akbar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <Navbar />
        <Header />
        <About />
        <Products />
        <Client />
        <Footer />
      </main>
    </div>
  );
}
